### ISSUE TITLE
USB Detection - Registry Key is invalid

### ISSUE THREAD

**Issue by tr1fled** [EvilBytecode/GoDefender#4]
Hello,

I tried to compile your project, ThunderKitty, but I noticed it doesn't work, upon enabling output and running it in powershell, the error is in the USB Detection module, where it runs a command to query the key `HKLM\\SYSTEM\\ControlSet001\\Enum\\USBSTOR`, one issue, I have looked for this key in two Windows 10 systems, VM and not VM, and nethier have that key, therefore making any project with USB Detection unusable.

I do not code in Go, if I did, I would create a PR with the fix, so my apologies if this sounds so demanding.

**Comment by KiExitDispatcher** [comment]
yeah, its mid but i have that key and many more of my friends, you can use other tactic.
