### ISSUE TITLE
GoDefender: mass of detection in final stub

### ISSUE THREAD

**Issue by yourdataleaked** [EvilBytecode/GoDefender#8]
This shit seems to be very old and freaked up with all AV's.
Final detect of clean stub - is 20/77, which is very bad.

Shitcode?

**Comment by KiExitDispatcher** [comment]
no shitcode, maybe beacuse it was used in ransomwares? lol im not helping cybercriminals 👍

**Comment by yourdataleaked** [comment]
> no shitcode, maybe beacuse it was used in ransomwares? lol im not helping cybercriminals 👍

I think you just a poor kid, who cannot make real AV and antidbg bypass

**Comment by KiExitDispatcher** [comment]
You seriously think throwing insults will magically fix your lack of skills? If you can’t handle something as simple as an AV bypass, maybe it’s time to stop blaming others for your incompetence. Keep crying about your failures while the rest of us actually get things done.

**Comment by KiExitDispatcher** [comment]
Av bypass isnt easy but some are.. so yea xoure doing static analysis so yea 👍😛

**Comment by yourdataleaked** [comment]
> You seriously think throwing insults will magically fix your lack of skills? If you can’t handle something as simple as an AV bypass, maybe it’s time to stop blaming others for your incompetence. Keep crying about your failures while the rest of us actually get things done.

you just poor nigerian kiddo, we already did a best crypt on the market.
Fck you from all Russian mal developers

**Comment by KiExitDispatcher** [comment]
Ah, resorting to tired stereotypes and weak insults? Looks like someone ran out of actual arguments. While you're busy hiding behind your 'best crypt on the market,' the rest of us are actually innovating, not recycling the same lame excuses. Keep pretending you’re relevant while real developers push the boundaries. The only thing you're best at is talking nonsense. 💀

**Comment by yourdataleaked** [comment]
> Ah, resorting to tired stereotypes and weak insults? Looks like someone ran out of actual arguments. While you're busy hiding behind your 'best crypt on the market,' the rest of us are actually innovating, not recycling the same lame excuses. Keep pretending you’re relevant while real developers push the boundaries. The only thing you're best at is talking nonsense. 💀

Maybe, because you wrote piece of shit and real garbage? This is really most buggy and detectable code on the opensource xD.
You don't understand, how to AV works, and say, that "cybercriminals sucks"
Нигер ебаный, пошел нахуй короче, бичара без нормальных прямых рук, пишущий говнокод который даже НОРМАЛЬНО НЕ РАБОТАЕТ!

**Comment by yourdataleaked** [comment]
> Av bypass isnt easy but some are.. so yea xoure doing static analysis so yea 👍😛

it's not easy, but if you tru little bit harder, u understand, how it's working

**Comment by EvilBytecode** [comment]
Nice try with the insults, but it’s obvious you’re just projecting your own failures. Your code is a dumpster fire, and your understanding of AV is laughable. Stop hiding behind static analysis and start innovating. Real developers don’t waste time on weak arguments. Get a grip. 💀

**Comment by ghost** [comment]
> This shit seems to be very old and freaked up with all AV's. Final detect of clean stub - is 20/77, which is very bad.
> 
> Shitcode?

you're telling me a github project, which has been HEAVILY sigged and used in multiple other sigged malwares, IS DETECTED?!?
that's just fucking inconceivable is it not? how could this have happened?

if you were in any sense of the word a good developer, you'd figure out how to rid yourself of the detections from this. It's like five minutes of work to remove every single detection caused by this, but evidently you're too stupid for this lol

**Comment by MmCopyMemory** [comment]
I agree with @SecDbg and @EvilBytecode 👍

**Comment by yourdataleaked** [comment]
> Nice try with the insults, but it’s obvious you’re just projecting your own failures. Your code is a dumpster fire, and your understanding of AV is laughable. Stop hiding behind static analysis and start innovating. Real developers don’t waste time on weak arguments. Get a grip. 💀

You didn't see my code, own stealers with dynamic encryption and real persistence, not shit autorun xD
You just a kid, who tried write "malware" and write totally shit, which is not compiling, have lack of features and heavy

Are you sure, to public this dirty indian code is really good idea?

**Comment by ghost** [comment]
> > Nice try with the insults, but it’s obvious you’re just projecting your own failures. Your code is a dumpster fire, and your understanding of AV is laughable. Stop hiding behind static analysis and start innovating. Real developers don’t waste time on weak arguments. Get a grip. 💀
> 
> You didn't see my code, own stealers with dynamic encryption and real persistence, not shit autorun xD You just a kid, who tried write "malware" and write totally shit, which is not compiling, have lack of features and heavy
> 
> Are you sure, to public this dirty indian code is really good idea?

dumbass if you're such a good developer then why are you too fucking pajeet to refud the anti-vm which is 5 minutes of work?
and why are you using go anti-vm if you're such a good dev?

**Comment by yourdataleaked** [comment]
> > > Nice try with the insults, but it’s obvious you’re just projecting your own failures. Your code is a dumpster fire, and your understanding of AV is laughable. Stop hiding behind static analysis and start innovating. Real developers don’t waste time on weak arguments. Get a grip. 💀
> > 
> > 
> > You didn't see my code, own stealers with dynamic encryption and real persistence, not shit autorun xD You just a kid, who tried write "malware" and write totally shit, which is not compiling, have lack of features and heavy
> > Are you sure, to public this dirty indian code is really good idea?
> 
> dumbass if you're such a good developer then why are you too fucking pajeet to refud the anti-vm which is 5 minutes of work? and why are you using go anti-vm if you're such a good dev?

Maybe because need to get rid of AV detection to not kill the final stub?
We fully rewritten this shit, and it's working like a charm, but get my ass burned for such shit-coding modules

**Comment by ghost** [comment]
> > > > Nice try with the insults, but it’s obvious you’re just projecting your own failures. Your code is a dumpster fire, and your understanding of AV is laughable. Stop hiding behind static analysis and start innovating. Real developers don’t waste time on weak arguments. Get a grip. 💀
> > > 
> > > 
> > > You didn't see my code, own stealers with dynamic encryption and real persistence, not shit autorun xD You just a kid, who tried write "malware" and write totally shit, which is not compiling, have lack of features and heavy
> > > Are you sure, to public this dirty indian code is really good idea?
> > 
> > 
> > dumbass if you're such a good developer then why are you too fucking pajeet to refud the anti-vm which is 5 minutes of work? and why are you using go anti-vm if you're such a good dev?
> 
> Maybe because need to get rid of AV detection to not kill the final stub? We fully rewritten this shit, and it's working like a charm, but get my ass burned for such shit-coding modules

exactly, so why don't you refud it?? it's 5 mins of work as I've said, i've done it for my own projects. the detections are easy to remove, and anything that isn't evasive enough can just be rewritten lol

**Comment by yourdataleaked** [comment]
> > > > > Nice try with the insults, but it’s obvious you’re just projecting your own failures. Your code is a dumpster fire, and your understanding of AV is laughable. Stop hiding behind static analysis and start innovating. Real developers don’t waste time on weak arguments. Get a grip. 💀
> > > > 
> > > > 
> > > > You didn't see my code, own stealers with dynamic encryption and real persistence, not shit autorun xD You just a kid, who tried write "malware" and write totally shit, which is not compiling, have lack of features and heavy
> > > > Are you sure, to public this dirty indian code is really good idea?
> > > 
> > > 
> > > dumbass if you're such a good developer then why are you too fucking pajeet to refud the anti-vm which is 5 minutes of work? and why are you using go anti-vm if you're such a good dev?
> > 
> > 
> > Maybe because need to get rid of AV detection to not kill the final stub? We fully rewritten this shit, and it's working like a charm, but get my ass burned for such shit-coding modules
> 
> exactly, so why don't you refud it?? it's 5 mins of work as I've said, i've done it for my own projects. the detections are easy to remove, and anything that isn't evasive enough can just be rewritten lol

dude, it's refuded already

**Comment by ghost** [comment]
> > > > > > Nice try with the insults, but it’s obvious you’re just projecting your own failures. Your code is a dumpster fire, and your understanding of AV is laughable. Stop hiding behind static analysis and start innovating. Real developers don’t waste time on weak arguments. Get a grip. 💀
> > > > > 
> > > > > 
> > > > > You didn't see my code, own stealers with dynamic encryption and real persistence, not shit autorun xD You just a kid, who tried write "malware" and write totally shit, which is not compiling, have lack of features and heavy
> > > > > Are you sure, to public this dirty indian code is really good idea?
> > > > 
> > > > 
> > > > dumbass if you're such a good developer then why are you too fucking pajeet to refud the anti-vm which is 5 minutes of work? and why are you using go anti-vm if you're such a good dev?
> > > 
> > > 
> > > Maybe because need to get rid of AV detection to not kill the final stub? We fully rewritten this shit, and it's working like a charm, but get my ass burned for such shit-coding modules
> > 
> > 
> > exactly, so why don't you refud it?? it's 5 mins of work as I've said, i've done it for my own projects. the detections are easy to remove, and anything that isn't evasive enough can just be rewritten lol
> 
> dude, it's refuded already

then what the fuck are you complaining about in issues for about detections if you got it fud already bro

**Comment by avary** [comment]
> This shit seems to be very old and freaked up with all AV's. Final detect of clean stub - is 20/77, which is very bad.
> 
> Shitcode?

talk is cheap, show us your code :D or you just a bigmouth retard.
